# 创建数组

## 创建简单数组

### numpy.array()

- numpy.array(object)

    object: 任何具有数组接口方法的对象。

In [3]:
import numpy as np
print(np1 := np.array([1, 2, 3]))
print(np2 := np.array([[1, 2], [3, 4]]))
print(np3 := np.array((1, 2, 3)))

[1 2 3]
[[1 2]
 [3 4]]
[1 2 3]


- numpy.array(object, dtype=None)

    dtype: 数据类型

In [10]:
import numpy as np
ls = [1, 2, 3]
print(np1 := np.array(ls))  # 默认会自动判断数据类型
print(type(np1[0]))
print(np2 := np.array(ls, dtype=float))  # 可以指定数据类型
print(type(np2[0]))

[1 2 3]
<class 'numpy.int32'>
[1. 2. 3.]
<class 'numpy.float64'>


- numpy.array(object, copy=True)

    cpoy: True则对象被复制；否则，只有当\__array__方法返回副本，~~object参数为嵌套序列~~，或者需要副本满足数据类型和顺序要求时，才会生成副本。

1. 正常情况下True时

In [12]:
import numpy as np
np1 = np.array([1, 2, 3])
np2 = np.array(np1)
np2[0] = 9
print(np1, np2)  # 发现np2被深拷贝了，np1没有随np2而改变
print(id(np1), id(np2))

[1 2 3] [9 2 3]
2969419251120 2969419249392


2. ~~object参数为嵌套列表时~~(暂时不理解,嵌套列表天生就只是引用)

In [18]:
import numpy as np
np1 = np.array([[1, 2, 3], [4, 5, 6]])
np2 = np.array(np1, copy=False)
np2[0] = 9
print(np1)
print(np2)
print(id(np1), id(np2))

[[9 9 9]
 [4 5 6]]
[[9 9 9]
 [4 5 6]]
2969425764368 2969425764368
[9 2 3 4 5 6]
[9 2 3 4 5 6]
2969425767248 2969425767248


3. 副本满足数据类型

In [19]:
import numpy as np
np1 = np.array([[1, 2, 3], [4, 5, 6]])
np2 = np.array(np1, copy=False, dtype=float)
np3 = np.array(np1, copy=False, dtype=int)
np1[0] = 9
print(np1)
print(np2)
print(np3)
print(id(np1), id(np2), id(np3))  # 数据类型发生了改变,会强行被深拷贝

[[9 9 9]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[9 9 9]
 [4 5 6]]
2969419647952 2969419650064 2969419647952


- numpy.array(object, ndmin=0)

    ndmin: 指定生成数组的最小维度

In [22]:
import numpy as np
l = [1, 2, 3]
np1 = np.array(l, ndmin=2)
print(np1)

[[1 2 3]]


## 不同方式创建数组

### numpy.empty()  创建未初始化数组

In [1]:
import numpy as np
np.empty([2, 3])

array([[2.00271247e-307, 4.89531867e-307, 8.34427737e-308],
       [8.34427737e-308, 1.50198342e-307, 2.44772215e-307]])

### numpy.zeros()

In [2]:
import numpy as np
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

### numpy.ones()

In [3]:
import numpy as np
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

## 数值范围创建数组

### numpy.arange()

与python内置函数range相似，返回[start, stop)

- numpy.arange([start,] stop[, step,], dtype=None)

    start: 起始值，默认值为0；
    stop: 终止值（不包含）；
    step: 步长，默认为1；

In [9]:
import numpy as np
print(np.arange(10))
print(np.arange(-1, 9))
print(np.arange(-1, 9, 2))
print(np.arange(-1, 9, 2.5))

[0 1 2 3 4 5 6 7 8 9]
[-1  0  1  2  3  4  5  6  7  8]
[-1  1  3  5  7]
[-1.   1.5  4.   6.5]
